#server:
#  port: 8080
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 1234
#    url: jdbc:mysql://localhost:3306/hrms_dummy
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  
   
server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: DbUser@123
    
    url: jdbc:mysql://68.178.164.213:3306/hrms_dummy
    username: hrmsapp_user
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
<<<<<<< HEAD
    
springdoc:
    packagesToScan: com.hrms.controller
    
=======

#server:
#  port: 9090
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: root
#    url: jdbc:mysql://localhost:3306/hrms_dummy
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
>>>>>>> 263fa520f10cf84dbe623210aab30fd233f2e7fc
